---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.
- name: selenium_started
  service: name=selenium_{{ selenium_sel_role }} state=started enabled=yes

- name: selenium_reload
  service: name=selenium_{{ selenium_sel_role }} state=reloaded
